### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by msakim** [keshavbhatt/ultimate-media-downloader-linux#31] opened 2024-08-18 17:49 UTC
error message:

UMD4] Starting download...
[youtube] Extracting URL: https://www.youtube.com/watch?v=8740UecgxGQ
[youtube] 8740UecgxGQ: Downloading webpage
[youtube] 8740UecgxGQ: Downloading ios player API JSON
[youtube] 8740UecgxGQ: Downloading web creator player API JSON
ERROR: [youtube] 8740UecgxGQ: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
[UMD4] Done

I have been trying to find the solution without success.

Could you help me?  Thanks.

**Comment by keshavbhatt** [comment] 2024-08-20 06:25
Duplicate of #29

**Closed** 2024-08-20 06:30 UTC

**Comment by keshavbhatt** [comment] 2024-09-09 22:14
If you have account on this website, try to install latest version 5.2 from edge channel. You can login to the website from built in browser and then download content as usual.
